### ISSUE TITLE
Error in parse_repo_spec(repo) : Invalid git repo specification: 'rga'

### ISSUE THREAD

**Issue by Hutch775** [skardhamar/rga#99]
When I try to install using:

install_github('rga', 'skardhamar')

I get the following error:

Error in parse_repo_spec(repo) : Invalid git repo specification: 'rga'

**Comment by EricGoldsmith** [comment]
That usage of `install_github()` has been deprecated (though, it used to work, but with a warning). Use this instead:
```
install_github('skardhamar/rga')
```

Looks like we need to update the README with that.

**Comment by Hutch775** [comment]
Thank you, I now get this error:

Error in curl::curl_fetch_memory(url, handle = h) : 
  Failed to connect to api.github.com port 443: Connection refused

**Comment by EricGoldsmith** [comment]
A [Google search on that error](https://www.google.com/search?q=Failed+to+connect+to+api.github.com+port+443%3A+Connection+refused&oq=Failed+to+connect+to+api.github.com+port+443%3A+Connection+refused&aqs=chrome..69i57.181j0j7&sourceid=chrome&ie=UTF-8) seems to indicate it's due to being behind a corporate proxy server. Is that the case? If so, maybe [these instructions](https://stackoverflow.com/questions/17783686/solution-how-to-install-github-when-there-is-a-proxy) from StackOverflow will help.

**Comment by Hutch775** [comment]
Many thanks.
